{% set name = "jnv" %}
{% set version = "0.6.0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/ynqa/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8220bf433728b57ddb174920a48c1750c5087b52154567074020b6800d6579d3

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - jnv --version

about:
  home: https://github.com/ynqa/jnv
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml
  summary: JSON navigator and interactive filter leveraging jq

extra:
  recipe-maintainers:
    - pavelzw
    - moritzwilksch
