{% set name = "jnv" %}
{% set version = "0.5.0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/ynqa/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 45cf21e6f33ea6c40a52d6d281a4ac4b67bcc02f8de6d615a56ad150a27ed666

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - jnv --version

about:
  home: https://github.com/ynqa/jnv
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml
  summary: JSON navigator and interactive filter leveraging jq

extra:
  recipe-maintainers:
    - pavelzw
    - moritzwilksch
